version: "3"
services:

  frontend:
    build: frontend/.
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    volumes:
      - ./frontend/src:/frontend/src
      - ./frontend/public:/frontend/public

  backend:
    # image: ubuntu:16.04
    build: backend/.
    ports:
      - "8080:8080"
    environment:
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
      - GEOSERVER_URL=http://localhost:8081/geoserver
      - DETECTION_API_URL=http://change-detection:5000
    volumes:
      - ./backend/src:/backend/src
      - ./geoserver/data:/geoserver-data
      - ./backend/data:/backend-data

  geoserver:
    container_name: geoserver
    build: geoserver/.
    ports:
      - "8081:8080"
    volumes:
      - ./geoserver/data:/opt/geoserver/data

