export const backendServer = 'http://localhost:5000'
export const datasetPath = backendServer + '/' + 'datasets'
export const inferencePath = backendServer + '/' + 'inference'
export const seriesModule = 'series'
export const datasetsModule = 'datasets'
